<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DirectoryStructureGenerator.PresetManager</AssemblyName>
    <RootNamespace>DirectoryStructureGenerator.PresetManager</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Config\presets.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config\settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <ApplicationIcon>PresetManager_ProductIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="PresetManager_ProductIcon.ico" />
  </ItemGroup>
</Project>